config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :users
  get 'signup', to: 'users#new', as: 'signup'
  get 'logout', to: 'users#destroy', as: 'logout'

  get 'coin/:name' => 'coins#coin', as: "coin"
  get 'coin2/:name' => 'coins2#coin', as: "coin2"
  get 'coin3/:name' => 'coins3#coin', as: "coin3"
  get 'coin4/:name' => 'coins4#coin', as: "coin4"
  get 'coin5/:name' => 'coins5#coin', as: "coin5"
  get 'coin5a/:name' => 'coins5#coin'
  get 'coin6/:name' => 'coins6#coin', as: "coin6"
  get 'coin6a/:name' => 'coins6#coin'
  get 'coin7/:name' => 'coins7#coin', as: "coin7"
  get 'coin7a/:name' => 'coins7#coin'
  get 'coin8/:name' => 'coins8#coin', as: "coin8"
  get 'coin8a/:name' => 'coins8#coin'
  get 'coin9/:name' => 'coins9#coin', as: "coin9"
  get 'coin9a/:name' => 'coins9#coin'
  get 'coin10/:name' => 'coins10#coin', as: "coin10"
  get 'coin10a/:name' => 'coins10#coin'
end

app/models/coin.rb
class Coin < ApplicationRecord

  def self.current_usd name
    coin_type = find_type(name)

    if coin_type == "Bitcoin"
      coin_rate = CoinRate.first
      if coin_rate.updated_at < 24.hours.ago
        usd = JSON.parse(RestClient.get("https://api.coindesk.com/v1/bpi/currentprice.json"))["bpi"]["USD"]["rate_float"] rescue 3856.0588
        coin_rate.update(usd: usd)
      else
        usd = coin_rate.usd.to_f
      end
    else
      usd = 1
    end
  end

  def self.coin_type name
    coin_type = find_type(name)

    if coin_type == "Bitcoin"
      return ["₿", "$", "USD"]
    elsif coin_type == "Tether"
      return ["$", "$", "USD"]
    else
      return ["","",""]
    end
  end

  def self.find_type name
    Coin.where(full_name: name).first.coin_type
  end

  def self.find_symbol name
    Coin.where(full_name: name).first.name
  end
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  # GET /coins
  # GET /coins.json
  # https://bittrex.com/api/v1.1/public/getmarkets
  # coins.each do |c|
  #   Coin.create(name: c.name, full_name: c.currency_name, coin_type: c.base_name, is_active: c.active)
  # end

  def coin
    @name = params[:name]
    if logged_in?
      CoinPosition.save_coin(@current_user.id, 1, @name)
    end

    @graph_data = history(@name)
    @sidebar_data = summary(@name)
    @coin_type = Coin.coin_type(@name)
    @usd = Coin.current_usd(@name)
  end

end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/views/coins/_chart.html.erb
<%= line_chart graph_data, curve: false, height: "350px", id: "chart1" %>
<div id="title">
  <%= render partial: 'home/title', locals: { sidebar_data: @sidebar_data, name: @name, coin_type: @coin_type, usd: @usd} %>
</div>

app/views/coins/_coin.html.erb
<div class="main-columns w-col w-col-6">
  <div class="row w-row">

    <div class="chart-column w-col w-col-8">
      <div class="column-wrapper">
        <div id="get_coin">
          <%= render partial: 'coins/navbar', locals: { get_coin: coin_path(@name), name: @name} %>
        </div>
        <div class="chart-section">
          <div id='loadingmessage' style='display:none'>
            <%= image_tag "loading.gif" %>
          </div>
          <div id="line_chart">
            <%= render partial: 'coins/chart', locals: { graph_data: @graph_data} %>
          </div>
        </div>
      </div>
    </div>

    <div class="coin-column w-col w-col-4">
      <div class="coin column-wrapper right-gap">
        <div class="nav w-nav">
          <div class="search-form w-clearfix">
            <%= text_field_tag :name, params[:name], placeholder: "Select Coin", class: "search-field w-input" %>
            <%= image_tag "magnifying-glass.svg", width: "28", class: 'search-btn' %>
          </div>
        </div>

        <div id="sidebar_menu" >
          <%= render partial: 'home/sidebar', locals: { sidebar_data: @sidebar_data, name: @name, coin_type: @coin_type, usd: @usd} %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/coins/_navbar.html.erb
<div class="nav w-nav" data-animation="default" data-collapse="medium" data-duration="400">
  <h3><%= name %></h3>
  <div class="nav-container w-container">
    <nav class="nav-menu w-nav-menu" role="navigation">
      <div class="nav-btn">
        <%= link_to image_tag('reload.svg'), get_coin, onclick: "$('#loadingmessage').show();$('#line_chart').hide();", remote: true %>
      </div>
    </nav>
  </div>
</div>

app/views/coins/coin.js.erb
$("#sidebar_menu").html("<%= escape_javascript(render partial: 'home/sidebar', locals: { sidebar_data: @sidebar_data, name: @name, coin_type: @coin_type, usd: @usd } ) %>");
$("#line_chart").html("<%= escape_javascript(render partial: 'coins/chart', locals: { graph_data: @graph_data } ) %>");
$("#get_coin").html("<%= escape_javascript(render partial: 'coins/navbar', locals: { get_coin: coin_path(@name), name: @name} ) %>");
$("#title").html("<%= escape_javascript(render partial: 'home/title', locals: { sidebar_data: @sidebar_data, name: @name, coin_type: @coin_type, usd: @usd } ) %>");

$('#loadingmessage').hide();
$('#line_chart').show();